#!/bin/bash
<< 'END'
user="$1"
if who | grep "^$user" > /dev/null
then
	echo  "$user is logged on"
fi
END


if [ -f "phonebook.txt" -a -r "phonebook.txt" ]
then
	echo "The file exists and readable"
else
	echo "The file does not exist"
fi
